"""
Константы для игры
"""

WIDTH, HEIGHT = 450, 380
DT = 0.5
GRAVITY_CONSTANT = 2
START_PAUSE = 1000
FRAME_TIME = 20  # microseconds
TANK_RADIUS = 15
MUZZLE_WIDTH = 10
MIN_BUBBLE_RADIUS = 30
MAX_BUBBLE_RADIUS = 40
SHELL_START_VELOCITY = 15
PLAYERS_NUMBER = 3
